# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LEUR3cIOzPOrTtJ7jLK2jAbddbK281hD
"""

def isHappy(n):
  n = str(n)
  n_list = list(n)

  new = 0
  seen_list = []

  while new != 1 and new not in seen_list:
    seen_list.append(int(new))
    new = 0

    for i in range(len(n_list)):
        new += int(n_list[i]) ** 2
    n_list = list(str(new))

  if new == 1:
    return True
  else:
    return False

if __name__ == "__main__":
  
  sample0_output = isHappy(19)
  sample1_output = isHappy(2)

  with open("/app/bind_mount/output.txt", "w") as f:
    f.write(f"19: {sample0_output}\n")
    f.write(f"2: {sample1_output}\n")

  print("Results saved to /app/bind_mount/output.txt")